# fly.toml app configuration file generated for qdrant-database on 2023-09-13T14:30:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "qdrant-database"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  QDRANT__STORAGE__SNAPSHOTS_PATH = "/data/qdrant/snapshots"
  QDRANT__STORAGE__STORAGE_PATH = "/data/qdrant/storage"

[[mounts]]
  source = "qdrant_data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 6333

  [[services.ports]]
    port = 6333
    handlers = ["http"]

  [[services.tcp_checks]]
    interval = "15s"
    grace_period = "10s"

